### ISSUE TITLE
[BUG] Existing account not found in proposal submission page

### ISSUE THREAD

**Issue by atb00ker** [fossunited/fossunited#390]
### Describe the bug

When I try to submit a talk proposal, I see the error:
```
Traceback (most recent call last):
  File "apps/frappe/frappe/website/serve.py", line 20, in get_response
    response = renderer_instance.render()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/website/page_renderers/document_page.py", line 41, in render
    html = self.get_html()
           ^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/website/utils.py", line 523, in cache_html_decorator
    html = func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/website/page_renderers/document_page.py", line 50, in get_html
    self.update_context()
  File "apps/frappe/frappe/website/page_renderers/document_page.py", line 65, in update_context
    ret = self.doc.get_context(self.context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/fossunited/fossunited/fossunited/doctype/foss_event_cfp_submission/foss_event_cfp_submission.py", line 43, in get_context
    context.speaker = frappe.get_doc(
                      ^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1333, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 85, in get_doc
    return controller(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/website/website_generator.py", line 16, in __init__
    super().__init__(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 126, in __init__
    self.load_from_db()
  File "apps/frappe/frappe/model/document.py", line 172, in load_from_db
    frappe.throw(
  File "apps/frappe/frappe/__init__.py", line 645, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 610, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 561, in _raise_exception
    raise exc
frappe.exceptions.DoesNotExistError: FOSS User Profile {'user': 'REMOVED_TO_AVOID_SCRAPING@gmail.com'} not found
```

See Live: https://fossunited.org/events/blr-june/cfp/91l1j40kqb
An account with the email in question exists and so does the profile: https://fossunited.org/REMOVED_TO_AVOID_SCRAPING

### To Reproduce

I am not sure. Here are two theories.

Theory#1: I changed my email address after creating the account and profile. Maybe there is/was a bug in email change procedure.
Theory#2: My email contains `+` symbol, which is valid email address but some websites don't like `+`.

### Environment

```markdown
- Device: Any
- OS: Any, btw I use Arch.
- Browser: Any
```

**Comment by harshtandiya** [comment]
![image](https://github.com/fossunited/fossunited/assets/73123690/3e0b2dcb-aee0-4e61-bfd6-66c8df19ca7c)

Hi @atb00ker, I think this is a bug on our part. There's an inconsistency between the emails you signed up with and the email in profile. This is due to the change in email as you mentioned. I will fix this so that it doesn't happen for future users. For the time being, I will change your "User" email with which you will log in to the email ending with fossunited

**Comment by harshtandiya** [comment]
Your proposal is submitted, rest assured.

**Comment by atb00ker** [comment]
Thanks for looking into it, I can now access the website as intended.
Cheers! 👍🏻

**Comment by rahulporuri** [comment]
added and moved to done. i think there was a PR which resolved this issue but it's not linked to the issue so i'm not sure which one

**Comment by harshtandiya** [comment]
@rahulporuri it was solved via desk
