### ISSUE TITLE
[BUG] Server error when signing in with Github

### ISSUE THREAD

**Issue by BhavyaSheth22** [fossunited/fossunited#558]
### Describe the bug

When trying to sign in to the website with Github, facing an issue. Also, some of these logs look like dev errors which are visible in Prod. Is that by design for troubleshooting?

> Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
           ^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1768, in call
    return fn(*args, **newargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/integrations/oauth2_logins.py", line 18, in login_via_github
    login_via_oauth2("github", code, state)
  File "apps/frappe/frappe/utils/oauth.py", line 115, in login_via_oauth2
    login_oauth_user(info, provider=provider, state=state)
  File "apps/frappe/frappe/utils/oauth.py", line 191, in login_oauth_user
    if update_oauth_user(user, data, provider) is False:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/utils/oauth.py", line 295, in update_oauth_user
    user.save()
  File "apps/frappe/frappe/model/document.py", line 337, in save
    return self._save(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 367, in _save
    self.check_if_latest()
  File "apps/frappe/frappe/model/document.py", line 815, in check_if_latest
    frappe.msgprint(
  File "apps/frappe/frappe/__init__.py", line 610, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 561, in _raise_exception
    raise exc
frappe.exceptions.TimestampMismatchError: Error: Document has been modified after you have opened it (2024-08-18 13:53:15.611317, 2024-08-18 13:53:15.828214). Please refresh to get the latest document.

On reloading, another error related to access token is seen:

> Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
           ^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1768, in call
    return fn(*args, **newargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/integrations/oauth2_logins.py", line 18, in login_via_github
    login_via_oauth2("github", code, state)
  File "apps/frappe/frappe/utils/oauth.py", line 115, in login_via_oauth2
    login_oauth_user(info, provider=provider, state=state)
  File "apps/frappe/frappe/utils/oauth.py", line 191, in login_oauth_user
    if update_oauth_user(user, data, provider) is False:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/utils/oauth.py", line 295, in update_oauth_user
    user.save()
  File "apps/frappe/frappe/model/document.py", line 337, in save
    return self._save(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 367, in _save
    self.check_if_latest()
  File "apps/frappe/frappe/model/document.py", line 815, in check_if_latest
    frappe.msgprint(
  File "apps/frappe/frappe/__init__.py", line 610, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 561, in _raise_exception
    raise exc
frappe.exceptions.TimestampMismatchError: Error: Document has been modified after you have opened it (2024-08-18 13:53:15.611317, 2024-08-18 13:53:15.828214). Please refresh to get the latest document.

### Expected behavior

Should to taken to dashboard after successful login via Github.

### To Reproduce

Login as a new user from GIthub

### Environment

```markdown
- Device: Desktop
- OS: Windows 11
- Browser: Edge
```

**Comment by RiyaMathew-11** [comment]
@BhavyaSheth22 - we've fixed the issue. Would you be able to test it once and verify too ? 
Please let us know

**Comment by harshtandiya** [comment]
Tested with Github account. Closing issue
